create sequence festival_seq start with 1 increment by 50;
create sequence offre_covoiturage_seq start with 1 increment by 50;
create sequence utilisateur_seq start with 1 increment by 50;
create table achat (num_achat number(19,0) not null, achat_validee number(1,0), nb_place number(19,0), id_festivalier varchar2(255 char), primary key (num_achat));
create table commune (codeinsee varchar2(255 char) not null, code_postal number(10,0), nom_commune varchar2(255 char), num_departement number(19,0), primary key (codeinsee));
create table departement (num_departement number(19,0) not null, nom_departement varchar2(255 char), nom_region varchar2(255 char), primary key (num_departement));
create table domaine (nom_domaine varchar2(255 char) not null, primary key (nom_domaine));
create table etape (idtrajet number(19,0) not null, heure timestamp(6) with time zone, prix float(24), id_lieu varchar2(255 char), id_offre_covoiturage number(19,0), primary key (idtrajet));
create table etape_achat (idtrajet number(19,0) not null, num_achat number(19,0) not null, nb_place number(10,0), primary key (idtrajet, num_achat));
create table festival (id_festival number(19,0) not null, date_debut date, date_fin date, nb_place number(10,0), nb_place_restante number(10,0), nom_manifestation varchar2(255 char), site_web varchar2(255 char), tarif number(10,2), codeinsee varchar2(255 char), nom_sous_domaine varchar2(255 char), primary key (id_festival));
create table festival_organisateur (user_uid varchar2(255 char) not null, id_festival number(19,0) not null);
create table lieu_covoiturage (id_lieu varchar2(255 char) not null, adresse_lieu varchar2(255 char), latitude number(25,20), longitude number(25,20), nom_lieu varchar2(255 char), type_lieu varchar2(255 char), codeinsee varchar2(255 char), primary key (id_lieu));
create table offre_covoiturage (id_offre_covoiturage number(19,0) not null, couleur varchar2(255 char), modele varchar2(255 char), nb_place number(10,0), num_immatriculation varchar2(255 char), id_conducteur varchar2(255 char), id_festival number(19,0), primary key (id_offre_covoiturage));
create table person (first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, primary key (first_name, last_name));
create table region (nom_region varchar2(255 char) not null, primary key (nom_region));
create table sous_domaine (nom_sous_domaine varchar2(255 char) not null, nom_domaine varchar2(255 char), primary key (nom_sous_domaine));
create table utilisateur (type_utilisateur varchar2(31 char) not null, user_uid varchar2(255 char) not null, email varchar2(255 char), nom varchar2(255 char), num_telephone varchar2(255 char), prenom varchar2(255 char), mdp varchar2(255 char), primary key (user_uid));
alter table achat add constraint FK5nifwtts3xjf4bxxn19ehvt9u foreign key (id_festivalier) references utilisateur;
alter table commune add constraint FKbr4hpf53wdm9qx1sxvpqlufxr foreign key (num_departement) references departement;
alter table departement add constraint FKnpv14iv3ljjl7uicfws4yepq0 foreign key (nom_region) references region;
alter table etape add constraint FKkbqbc1jomjqu2clvy6ant3lxp foreign key (id_lieu) references lieu_covoiturage;
alter table etape add constraint FK2uq2r0anrh4eo4m71nccrafyg foreign key (id_offre_covoiturage) references offre_covoiturage;
alter table etape_achat add constraint FKlwvd9dqkdt2puvy9vn2nj7g2u foreign key (num_achat) references achat;
alter table etape_achat add constraint FKismhtn99q5lrn77ppra4vrvu2 foreign key (idtrajet) references etape;
alter table festival add constraint FK5owqg5wnlp28j5sbpjqg0otwh foreign key (codeinsee) references commune;
alter table festival add constraint FKijtqejqeg3pin0mk0hnxfs95a foreign key (nom_sous_domaine) references sous_domaine;
alter table festival_organisateur add constraint FKs1h3oqci12rrwfnr8t9xvc821 foreign key (id_festival) references festival;
alter table festival_organisateur add constraint FKdwymsx62ggqvl0i4m7eoun71p foreign key (user_uid) references utilisateur;
alter table lieu_covoiturage add constraint FKnd70e1fxn67344lieb9df9oyn foreign key (codeinsee) references commune;
alter table offre_covoiturage add constraint FK90sgdfouf6dply5d6yx3gb7tk foreign key (id_conducteur) references utilisateur;
alter table offre_covoiturage add constraint FKl163qnej2bp0mmirdtwl4hral foreign key (id_festival) references festival;
alter table sous_domaine add constraint FKrvpmo1ro9xamor4bcw3kg3fa0 foreign key (nom_domaine) references domaine;
create sequence festival_seq start with 1 increment by 50;
create sequence offre_covoiturage_seq start with 1 increment by 50;
create sequence utilisateur_seq start with 1 increment by 50;
create table achat (num_achat number(19,0) not null, achat_validee number(1,0), nb_place number(19,0), id_festivalier varchar2(255 char), primary key (num_achat));
create table commune (codeinsee varchar2(255 char) not null, code_postal number(10,0), nom_commune varchar2(255 char), num_departement number(19,0), primary key (codeinsee));
create table departement (num_departement number(19,0) not null, nom_departement varchar2(255 char), nom_region varchar2(255 char), primary key (num_departement));
create table domaine (nom_domaine varchar2(255 char) not null, primary key (nom_domaine));
create table etape (idtrajet number(19,0) not null, heure timestamp(6) with time zone, prix float(24), id_lieu varchar2(255 char), id_offre_covoiturage number(19,0), primary key (idtrajet));
create table etape_achat (idtrajet number(19,0) not null, num_achat number(19,0) not null, nb_place number(10,0), primary key (idtrajet, num_achat));
create table festival (id_festival number(19,0) not null, date_debut date, date_fin date, nb_place number(10,0), nb_place_restante number(10,0), nom_manifestation varchar2(255 char), site_web varchar2(255 char), tarif number(10,2), codeinsee varchar2(255 char), nom_sous_domaine varchar2(255 char), primary key (id_festival));
create table festival_organisateur (user_uid varchar2(255 char) not null, id_festival number(19,0) not null);
create table lieu_covoiturage (id_lieu varchar2(255 char) not null, adresse_lieu varchar2(255 char), latitude number(25,20), longitude number(25,20), nom_lieu varchar2(255 char), type_lieu varchar2(255 char), codeinsee varchar2(255 char), primary key (id_lieu));
create table offre_covoiturage (id_offre_covoiturage number(19,0) not null, couleur varchar2(255 char), modele varchar2(255 char), nb_place number(10,0), num_immatriculation varchar2(255 char), id_conducteur varchar2(255 char), id_festival number(19,0), primary key (id_offre_covoiturage));
create table person (first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, primary key (first_name, last_name));
create table region (nom_region varchar2(255 char) not null, primary key (nom_region));
create table sous_domaine (nom_sous_domaine varchar2(255 char) not null, nom_domaine varchar2(255 char), primary key (nom_sous_domaine));
create table utilisateur (type_utilisateur varchar2(31 char) not null, user_uid varchar2(255 char) not null, email varchar2(255 char), nom varchar2(255 char), num_telephone varchar2(255 char), prenom varchar2(255 char), mdp varchar2(255 char), primary key (user_uid));
alter table achat add constraint FK5nifwtts3xjf4bxxn19ehvt9u foreign key (id_festivalier) references utilisateur;
alter table commune add constraint FKbr4hpf53wdm9qx1sxvpqlufxr foreign key (num_departement) references departement;
alter table departement add constraint FKnpv14iv3ljjl7uicfws4yepq0 foreign key (nom_region) references region;
alter table etape add constraint FKkbqbc1jomjqu2clvy6ant3lxp foreign key (id_lieu) references lieu_covoiturage;
alter table etape add constraint FK2uq2r0anrh4eo4m71nccrafyg foreign key (id_offre_covoiturage) references offre_covoiturage;
alter table etape_achat add constraint FKlwvd9dqkdt2puvy9vn2nj7g2u foreign key (num_achat) references achat;
alter table etape_achat add constraint FKismhtn99q5lrn77ppra4vrvu2 foreign key (idtrajet) references etape;
alter table festival add constraint FK5owqg5wnlp28j5sbpjqg0otwh foreign key (codeinsee) references commune;
alter table festival add constraint FKijtqejqeg3pin0mk0hnxfs95a foreign key (nom_sous_domaine) references sous_domaine;
alter table festival_organisateur add constraint FKs1h3oqci12rrwfnr8t9xvc821 foreign key (id_festival) references festival;
alter table festival_organisateur add constraint FKdwymsx62ggqvl0i4m7eoun71p foreign key (user_uid) references utilisateur;
alter table lieu_covoiturage add constraint FKnd70e1fxn67344lieb9df9oyn foreign key (codeinsee) references commune;
alter table offre_covoiturage add constraint FK90sgdfouf6dply5d6yx3gb7tk foreign key (id_conducteur) references utilisateur;
alter table offre_covoiturage add constraint FKl163qnej2bp0mmirdtwl4hral foreign key (id_festival) references festival;
alter table sous_domaine add constraint FKrvpmo1ro9xamor4bcw3kg3fa0 foreign key (nom_domaine) references domaine;
create sequence festival_seq start with 1 increment by 50;
create sequence offre_covoiturage_seq start with 1 increment by 50;
create sequence utilisateur_seq start with 1 increment by 50;
create table achat (num_achat number(19,0) not null, achat_validee number(1,0), nb_place number(19,0), id_festivalier varchar2(255 char), primary key (num_achat));
create table commune (codeinsee varchar2(255 char) not null, code_postal number(10,0), nom_commune varchar2(255 char), num_departement number(19,0), primary key (codeinsee));
create table departement (num_departement number(19,0) not null, nom_departement varchar2(255 char), nom_region varchar2(255 char), primary key (num_departement));
create table domaine (nom_domaine varchar2(255 char) not null, primary key (nom_domaine));
create table etape (idtrajet number(19,0) not null, heure timestamp(6) with time zone, prix float(24), id_lieu varchar2(255 char), id_offre_covoiturage number(19,0), primary key (idtrajet));
create table etape_achat (idtrajet number(19,0) not null, num_achat number(19,0) not null, nb_place number(10,0), primary key (idtrajet, num_achat));
create table festival (id_festival number(19,0) not null, date_debut date, date_fin date, nb_place number(10,0), nb_place_restante number(10,0), nom_manifestation varchar2(255 char), site_web varchar2(255 char), tarif number(10,2), codeinsee varchar2(255 char), nom_sous_domaine varchar2(255 char), primary key (id_festival));
create table festival_organisateur (user_uid varchar2(255 char) not null, id_festival number(19,0) not null);
create table lieu_covoiturage (id_lieu varchar2(255 char) not null, adresse_lieu varchar2(255 char), latitude number(25,20), longitude number(25,20), nom_lieu varchar2(255 char), type_lieu varchar2(255 char), codeinsee varchar2(255 char), primary key (id_lieu));
create table offre_covoiturage (id_offre_covoiturage number(19,0) not null, couleur varchar2(255 char), modele varchar2(255 char), nb_place number(10,0), num_immatriculation varchar2(255 char), id_conducteur varchar2(255 char), id_festival number(19,0), primary key (id_offre_covoiturage));
create table person (first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, primary key (first_name, last_name));
create table region (nom_region varchar2(255 char) not null, primary key (nom_region));
create table sous_domaine (nom_sous_domaine varchar2(255 char) not null, nom_domaine varchar2(255 char), primary key (nom_sous_domaine));
create table utilisateur (type_utilisateur varchar2(31 char) not null, user_uid varchar2(255 char) not null, email varchar2(255 char), nom varchar2(255 char), num_telephone varchar2(255 char), prenom varchar2(255 char), mdp varchar2(255 char), primary key (user_uid));
alter table achat add constraint FK5nifwtts3xjf4bxxn19ehvt9u foreign key (id_festivalier) references utilisateur;
alter table commune add constraint FKbr4hpf53wdm9qx1sxvpqlufxr foreign key (num_departement) references departement;
alter table departement add constraint FKnpv14iv3ljjl7uicfws4yepq0 foreign key (nom_region) references region;
alter table etape add constraint FKkbqbc1jomjqu2clvy6ant3lxp foreign key (id_lieu) references lieu_covoiturage;
alter table etape add constraint FK2uq2r0anrh4eo4m71nccrafyg foreign key (id_offre_covoiturage) references offre_covoiturage;
alter table etape_achat add constraint FKlwvd9dqkdt2puvy9vn2nj7g2u foreign key (num_achat) references achat;
alter table etape_achat add constraint FKismhtn99q5lrn77ppra4vrvu2 foreign key (idtrajet) references etape;
alter table festival add constraint FK5owqg5wnlp28j5sbpjqg0otwh foreign key (codeinsee) references commune;
alter table festival add constraint FKijtqejqeg3pin0mk0hnxfs95a foreign key (nom_sous_domaine) references sous_domaine;
alter table festival_organisateur add constraint FKs1h3oqci12rrwfnr8t9xvc821 foreign key (id_festival) references festival;
alter table festival_organisateur add constraint FKdwymsx62ggqvl0i4m7eoun71p foreign key (user_uid) references utilisateur;
alter table lieu_covoiturage add constraint FKnd70e1fxn67344lieb9df9oyn foreign key (codeinsee) references commune;
alter table offre_covoiturage add constraint FK90sgdfouf6dply5d6yx3gb7tk foreign key (id_conducteur) references utilisateur;
alter table offre_covoiturage add constraint FKl163qnej2bp0mmirdtwl4hral foreign key (id_festival) references festival;
alter table sous_domaine add constraint FKrvpmo1ro9xamor4bcw3kg3fa0 foreign key (nom_domaine) references domaine;
create sequence festival_seq start with 1 increment by 50;
create sequence offre_covoiturage_seq start with 1 increment by 50;
create sequence utilisateur_seq start with 1 increment by 50;
create table achat (num_achat number(19,0) not null, achat_validee number(1,0), nb_place number(19,0), id_festivalier varchar2(255 char), primary key (num_achat));
create table commune (codeinsee varchar2(255 char) not null, code_postal number(10,0), nom_commune varchar2(255 char), num_departement number(19,0), primary key (codeinsee));
create table departement (num_departement number(19,0) not null, nom_departement varchar2(255 char), nom_region varchar2(255 char), primary key (num_departement));
create table domaine (nom_domaine varchar2(255 char) not null, primary key (nom_domaine));
create table etape (idtrajet number(19,0) not null, heure timestamp(6) with time zone, prix float(24), id_lieu varchar2(255 char), id_offre_covoiturage number(19,0), primary key (idtrajet));
create table etape_achat (idtrajet number(19,0) not null, num_achat number(19,0) not null, nb_place number(10,0), primary key (idtrajet, num_achat));
create table festival (id_festival number(19,0) not null, date_debut date, date_fin date, nb_place number(10,0), nb_place_restante number(10,0), nom_manifestation varchar2(255 char), site_web varchar2(255 char), tarif number(10,2), codeinsee varchar2(255 char), nom_sous_domaine varchar2(255 char), primary key (id_festival));
create table festival_organisateur (user_uid varchar2(255 char) not null, id_festival number(19,0) not null);
create table lieu_covoiturage (id_lieu varchar2(255 char) not null, adresse_lieu varchar2(255 char), latitude number(25,20), longitude number(25,20), nom_lieu varchar2(255 char), type_lieu varchar2(255 char), codeinsee varchar2(255 char), primary key (id_lieu));
create table offre_covoiturage (id_offre_covoiturage number(19,0) not null, couleur varchar2(255 char), modele varchar2(255 char), nb_place number(10,0), num_immatriculation varchar2(255 char), id_conducteur varchar2(255 char), id_festival number(19,0), primary key (id_offre_covoiturage));
create table person (first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, primary key (first_name, last_name));
create table region (nom_region varchar2(255 char) not null, primary key (nom_region));
create table sous_domaine (nom_sous_domaine varchar2(255 char) not null, nom_domaine varchar2(255 char), primary key (nom_sous_domaine));
create table utilisateur (type_utilisateur varchar2(31 char) not null, user_uid varchar2(255 char) not null, email varchar2(255 char), nom varchar2(255 char), num_telephone varchar2(255 char), prenom varchar2(255 char), mdp varchar2(255 char), primary key (user_uid));
alter table achat add constraint FK5nifwtts3xjf4bxxn19ehvt9u foreign key (id_festivalier) references utilisateur;
alter table commune add constraint FKbr4hpf53wdm9qx1sxvpqlufxr foreign key (num_departement) references departement;
alter table departement add constraint FKnpv14iv3ljjl7uicfws4yepq0 foreign key (nom_region) references region;
alter table etape add constraint FKkbqbc1jomjqu2clvy6ant3lxp foreign key (id_lieu) references lieu_covoiturage;
alter table etape add constraint FK2uq2r0anrh4eo4m71nccrafyg foreign key (id_offre_covoiturage) references offre_covoiturage;
alter table etape_achat add constraint FKlwvd9dqkdt2puvy9vn2nj7g2u foreign key (num_achat) references achat;
alter table etape_achat add constraint FKismhtn99q5lrn77ppra4vrvu2 foreign key (idtrajet) references etape;
alter table festival add constraint FK5owqg5wnlp28j5sbpjqg0otwh foreign key (codeinsee) references commune;
alter table festival add constraint FKijtqejqeg3pin0mk0hnxfs95a foreign key (nom_sous_domaine) references sous_domaine;
alter table festival_organisateur add constraint FKs1h3oqci12rrwfnr8t9xvc821 foreign key (id_festival) references festival;
alter table festival_organisateur add constraint FKdwymsx62ggqvl0i4m7eoun71p foreign key (user_uid) references utilisateur;
alter table lieu_covoiturage add constraint FKnd70e1fxn67344lieb9df9oyn foreign key (codeinsee) references commune;
alter table offre_covoiturage add constraint FK90sgdfouf6dply5d6yx3gb7tk foreign key (id_conducteur) references utilisateur;
alter table offre_covoiturage add constraint FKl163qnej2bp0mmirdtwl4hral foreign key (id_festival) references festival;
alter table sous_domaine add constraint FKrvpmo1ro9xamor4bcw3kg3fa0 foreign key (nom_domaine) references domaine;
create sequence festival_seq start with 1 increment by 50;
create sequence offre_covoiturage_seq start with 1 increment by 50;
create sequence utilisateur_seq start with 1 increment by 50;
create table achat (num_achat number(19,0) not null, achat_validee number(1,0), nb_place number(19,0), id_festivalier varchar2(255 char), primary key (num_achat));
create table commune (codeinsee varchar2(255 char) not null, code_postal number(10,0), nom_commune varchar2(255 char), num_departement number(19,0), primary key (codeinsee));
create table departement (num_departement number(19,0) not null, nom_departement varchar2(255 char), nom_region varchar2(255 char), primary key (num_departement));
create table domaine (nom_domaine varchar2(255 char) not null, primary key (nom_domaine));
create table etape (idtrajet number(19,0) not null, heure timestamp(6) with time zone, prix float(24), id_lieu varchar2(255 char), id_offre_covoiturage number(19,0), primary key (idtrajet));
create table etape_achat (idtrajet number(19,0) not null, num_achat number(19,0) not null, nb_place number(10,0), primary key (idtrajet, num_achat));
create table festival (id_festival number(19,0) not null, date_debut date, date_fin date, nb_place number(10,0), nb_place_restante number(10,0), nom_manifestation varchar2(255 char), site_web varchar2(255 char), tarif number(10,2), codeinsee varchar2(255 char), nom_sous_domaine varchar2(255 char), primary key (id_festival));
create table festival_organisateur (user_uid varchar2(255 char) not null, id_festival number(19,0) not null);
create table lieu_covoiturage (id_lieu varchar2(255 char) not null, adresse_lieu varchar2(255 char), latitude number(25,20), longitude number(25,20), nom_lieu varchar2(255 char), type_lieu varchar2(255 char), codeinsee varchar2(255 char), primary key (id_lieu));
create table offre_covoiturage (id_offre_covoiturage number(19,0) not null, couleur varchar2(255 char), modele varchar2(255 char), nb_place number(10,0), num_immatriculation varchar2(255 char), id_conducteur varchar2(255 char), id_festival number(19,0), primary key (id_offre_covoiturage));
create table person (first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, primary key (first_name, last_name));
create table region (nom_region varchar2(255 char) not null, primary key (nom_region));
create table sous_domaine (nom_sous_domaine varchar2(255 char) not null, nom_domaine varchar2(255 char), primary key (nom_sous_domaine));
create table utilisateur (type_utilisateur varchar2(31 char) not null, user_uid varchar2(255 char) not null, email varchar2(255 char), nom varchar2(255 char), num_telephone varchar2(255 char), prenom varchar2(255 char), mdp varchar2(255 char), primary key (user_uid));
alter table achat add constraint FK5nifwtts3xjf4bxxn19ehvt9u foreign key (id_festivalier) references utilisateur;
alter table commune add constraint FKbr4hpf53wdm9qx1sxvpqlufxr foreign key (num_departement) references departement;
alter table departement add constraint FKnpv14iv3ljjl7uicfws4yepq0 foreign key (nom_region) references region;
alter table etape add constraint FKkbqbc1jomjqu2clvy6ant3lxp foreign key (id_lieu) references lieu_covoiturage;
alter table etape add constraint FK2uq2r0anrh4eo4m71nccrafyg foreign key (id_offre_covoiturage) references offre_covoiturage;
alter table etape_achat add constraint FKlwvd9dqkdt2puvy9vn2nj7g2u foreign key (num_achat) references achat;
alter table etape_achat add constraint FKismhtn99q5lrn77ppra4vrvu2 foreign key (idtrajet) references etape;
alter table festival add constraint FK5owqg5wnlp28j5sbpjqg0otwh foreign key (codeinsee) references commune;
alter table festival add constraint FKijtqejqeg3pin0mk0hnxfs95a foreign key (nom_sous_domaine) references sous_domaine;
alter table festival_organisateur add constraint FKs1h3oqci12rrwfnr8t9xvc821 foreign key (id_festival) references festival;
alter table festival_organisateur add constraint FKdwymsx62ggqvl0i4m7eoun71p foreign key (user_uid) references utilisateur;
alter table lieu_covoiturage add constraint FKnd70e1fxn67344lieb9df9oyn foreign key (codeinsee) references commune;
alter table offre_covoiturage add constraint FK90sgdfouf6dply5d6yx3gb7tk foreign key (id_conducteur) references utilisateur;
alter table offre_covoiturage add constraint FKl163qnej2bp0mmirdtwl4hral foreign key (id_festival) references festival;
alter table sous_domaine add constraint FKrvpmo1ro9xamor4bcw3kg3fa0 foreign key (nom_domaine) references domaine;
