INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (31, 'Haute-Garonne', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (13, 'Bouches-du-Rhône', 'Provence-Alpes-Côte d Azur');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (33, 'Gironde', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (38, 'Isère', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (42, 'Loire', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (22, 'Côtes-d Armor', 'Bretagne');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (66, 'Pyrénées-Orientales', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (34, 'Hérault', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (69, 'Rhône', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (1, 'Ain', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (86, 'Vienne', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (85, 'Vendée', 'Pays de la Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (49, 'Maine-et-Loire', 'Pays de la Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (21, 'Côte-d Or', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (81, 'Tarn', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (64, 'Pyrénées-Atlantiques', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (78, 'Yvelines', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (53, 'Mayenne', 'Pays de la Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (59, 'Nord', 'Hauts-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (26, 'Drôme', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (6, 'Alpes-Maritimes', 'Provence-Alpes-Côte d Azur');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (80, 'Somme', 'Hauts-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (29, 'Finistère', 'Bretagne');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (47, 'Lot-et-Garonne', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (76, 'Seine-Maritime', 'Normandie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (46, 'Lot', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (93, 'Seine-Saint-Denis', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (89, 'Yonne', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (75, 'Paris', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (11, 'Aude', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (91, 'Essonne', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (73, 'Savoie', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (56, 'Morbihan', 'Bretagne');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (5, 'Hautes-Alpes', 'Provence-Alpes-Côte d Azur');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (65, 'Hautes-Pyrénées', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (37, 'Indre-et-Loire', 'Centre-Val de Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (74, 'Haute-Savoie', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (14, 'Calvados', 'Normandie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (40, 'Landes', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (43, 'Haute-Loire', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (35, 'Ille-et-Vilaine', 'Bretagne');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (84, 'Vaucluse', 'Provence-Alpes-Côte d Azur');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (7, 'Ardèche', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (62, 'Pas-de-Calais', 'Hauts-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (54, 'Meurthe-et-Moselle', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (61, 'Orne', 'Normandie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (20, 'Haute-Corse', 'Corse');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (60, 'Oise', 'Hauts-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (30, 'Gard', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (63, 'Puy-de-Dôme', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (79, 'Deux-Sèvres', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (3, 'Allier', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (67, 'Bas-Rhin', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (55, 'Meuse', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (50, 'Manche', 'Normandie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (95, 'Val-d Oise', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (44, 'Loire-Atlantique', 'Pays de la Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (71, 'Saône-et-Loire', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (8, 'Ardennes', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (39, 'Jura', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (18, 'Cher', 'Centre-Val de Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (45, 'Loiret', 'Centre-Val de Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (92, 'Hauts-de-Seine', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (90, 'Territoire de Belfort', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (24, 'Dordogne', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (72, 'Sarthe', 'Pays de la Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (52, 'Haute-Marne', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (2, 'Aisne', 'Hauts-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (15, 'Cantal', 'Auvergne-Rhône-Alpes');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (94, 'Val-de-Marne', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (68, 'Haut-Rhin', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (36, 'Indre', 'Centre-Val de Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (25, 'Doubs', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (58, 'Nièvre', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (83, 'Var', 'Provence-Alpes-Côte d Azur');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (19, 'Corrèze', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (23, 'Creuse', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (51, 'Marne', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (20, 'Corse-du-Sud', 'Corse');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (27, 'Eure', 'Normandie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (77, 'Seine-et-Marne', 'Île-de-France');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (12, 'Aveyron', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (28, 'Eure-et-Loir', 'Centre-Val de Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (32, 'Gers', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (976, 'Mayotte', 'Mayotte');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (17, 'Charente-Maritime', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (16, 'Charente', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (70, 'Haute-Saône', 'Bourgogne-Franche-Comté');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (4, 'Alpes-de-Haute-Provence', 'Provence-Alpes-Côte d Azur');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (10, 'Aube', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (87, 'Haute-Vienne', 'Nouvelle-Aquitaine');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (57, 'Moselle', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (41, 'Loir-et-Cher', 'Centre-Val de Loire');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (48, 'Lozère', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (88, 'Vosges', 'Grand Est');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (973, 'Guyane', 'Guyane');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (974, 'La Réunion', 'La Réunion');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (972, 'Martinique', 'Martinique');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (971, 'Guadeloupe', 'Guadeloupe');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (82, 'Tarn-et-Garonne', 'Occitanie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (988, 'Nouvelle-Calédonie', 'Nouvelle Calédonie');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (987, 'Polynésie française', 'Polynésie française');
INSERT INTO Departement (numDepartement, nomDepartement, nomRegion) VALUES (9, 'Ariège', 'Occitanie');
