INSERT INTO Domaine (nomDomaine) VALUES ('Musiques actuelles');
INSERT INTO Domaine (nomDomaine) VALUES ('Transdisciplinaire');
INSERT INTO Domaine (nomDomaine) VALUES ('Pluridisciplinaire Spectacle vivant');
INSERT INTO Domaine (nomDomaine) VALUES ('Cirque et Arts de la rue');
INSERT INTO Domaine (nomDomaine) VALUES ('Pluridisciplinaire Musique');
INSERT INTO Domaine (nomDomaine) VALUES ('Musiques classiques');
INSERT INTO Domaine (nomDomaine) VALUES ('Livre et littérature');
INSERT INTO Domaine (nomDomaine) VALUES ('Arts plastiques et visuels');
INSERT INTO Domaine (nomDomaine) VALUES ('Danse');
INSERT INTO Domaine (nomDomaine) VALUES ('Cinéma et audiovisuel');
INSERT INTO Domaine (nomDomaine) VALUES ('Domaines divers');
INSERT INTO Domaine (nomDomaine) VALUES ('Théâtre');
INSERT INTO Domaine (nomDomaine) VALUES ('Divers spectacle vivant');