
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques traditionnelles et du monde', 'Musiques actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Transdisciplinaire', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Pluridisciplinaire Spectacle vivant', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques amplifiées ou électroniques', 'Musiques actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Arts de la rue', 'Cirque et Arts de la rue');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques actuelles', 'Musiques actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Pluridisciplinaire Musique', 'Pluridisciplinaire Musique');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Jazz, blues et musiques improvisées', 'Musiques actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques classiques', 'Musiques classiques');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Chanson', 'Musiques actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Humour', 'Divers Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Baroque et ancien', 'Musiques classiques');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Bande dessinée', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cultures d Afrique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Arts platiques et musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique de chambre', 'Musiques classiques');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Arts plastiques et visuels', 'Arts plastiques et visuels');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danse contemporaine', 'Danse');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cinémas étrangers', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danse et musique', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Jeune public', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Marionnettes', 'Divers Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique contemporaine', 'Musiques classiques');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Traduction', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre et littérature', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cirque et Arts de la rue', 'Cirque et Arts de la rue');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cirque', 'Cirque et Arts de la rue');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Sciences humaines et sociales', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Littératures étrangères', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Architecture et paysage', 'Domaines divers');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Photographie', 'Arts plastiques et visuels');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Design', 'Arts plastiques et visuels');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Histoire et patrimoine', 'Domaines divers');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Poésie', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Littérature policière', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Films fantastique', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique et danse', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danses urbaines', 'Danse');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Documentaire', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Création numérique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danse', 'Danse');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Audiovisuel', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cinéma et audiovisuel', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Illustration', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Nature et littérature', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Lyrique et choral', 'Musiques classiques');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Enfance et jeunesse', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Animation', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Pop culture', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Culture hip hop', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Conte', 'Divers Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Courts-métrages', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danses et musiques urbaines', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danses du monde et traditionnelles', 'Danse');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cultures électroniques', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Théâtre', 'Théâtre');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique et bande dessinée', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Humour, conte, musique', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Marionnettes', 'Divers Spectacle Vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques, danses, cinéma, expositions', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre et cinéma', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Art numérique', 'Arts plastiques et visuels');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Jeune public', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Culture andalouse', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Sciences et techniques', 'Domaines divers');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Géopolitique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Journalisme', 'Domaines divers');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cinéma et nature', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Bandes annonces', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Biographie', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Magie', 'Divers Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danse et arts multiples', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cirque, danse, performance, musique', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Danses et musiques du monde', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques actuelles et arts de la rue', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Théâtre espagnol', 'Théâtre');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre audio', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre de jeunesse', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cinéma, littérature', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Patrimoine cinématographique', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Mode et photographie', 'Arts plastiques et visuels');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Jardins', 'Domaines divers');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Film policier', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Premiers films', 'Cinéma et audiovisuel');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Théâtre amateur', 'Théâtre');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Arts du carnet', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Littérature et chanson', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique et arts visuels', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Street art', 'Arts plastiques et visuels');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Lectures et spectacles', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Théâtre, marionnettes, objets,musique, arts plastiques, vidéo', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Jeune public', 'Théâtre');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Arts plastiques et musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Jeune public', 'Musiques actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Improvisation théatrale', 'Théâtre');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Jardins et spectacle vivant', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Spectacle vivant, arts visuels, goût', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cinéma et Musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Lecture, spectacles', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique, cirque, humour', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Nature et Arts plastiques', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Marionnettes', 'Divers spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques électro', 'Pluridisciplinaire Musique');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Expositions, concerts', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques et danses du monde', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre et vin', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Art urbain, art contemporain, musiques actuelles.', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cultures urbaines', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques Actuelles', 'Musiques Actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cinéma et musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Spectacle vivant, arts visuels, arts plastiques et cinéma', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre et arts visuels', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cinéma, musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Littérature et Spectacle Vivant', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique et cuisine', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Science fiction', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Littérature et Jazz', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques actuelles et Arts de la rue', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Science fiction', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Littérature et musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Mime', 'Divers Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cultures africaines', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Electro', 'Musiques actuelles');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique et littérature', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Sport et Musiques actuelles', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques et arts visuels', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Arts et  cultures du Proche-Orient', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Expositions, musiques actuelles', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques et arts de la rue', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cultures nordiques', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Conte', 'Divers spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Ecritures', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Théâtre et lecture', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Spectacle vivant et arts de la table', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Vin et musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre historique', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('revues', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre de montagne', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Livre ancien', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Poche', 'Livre et littérature');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique et arts plastiques', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Swing', 'Danse');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique, théâtre, cinéma, gastronomie', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Théâtre, poésie, musique', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Théâtre et littérature', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Cultures urbaines', 'Pluridisciplinaire Spectacle vivant');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique, sport et écologie', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musiques actuelles et vins naturels', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Musique et moto', 'Transdisciplinaire');
INSERT INTO sous_domaine (nom_sous_domaine, nom_domaine) VALUES ('Moto et musique', 'Transdisciplinaire');

